import { TemplateItem } from "./types";
import { ASPECT_RATIOS } from "../values";
import { DEFAULT_IMAGE_STYLE } from "../types";

export const BUILTIN_TEMPLATES: TemplateItem[] = [
  {
    id: "tilted-triptych",
    title: "Tilted Triptych",
    description: "Triple perspective cards with subtle 3D yaw and gentle depth overlap.",
    category: "presentation",
    layoutType: "triptych-3d",
    aspectRatio: ASPECT_RATIOS.find((r) => r.name === "16:9") || ASPECT_RATIOS[0],
    elements: [
      {
        id: "triptych_left",
        type: "image",
        name: "Left Card",
        src: "",
        isPlaceholder: true,
        placeholderLabel: "Left Card",
        width: 260,
        height: 380,
        position: { x: 100, y: 75 },
        style: {
          ...DEFAULT_IMAGE_STYLE,
          rotateX: 6,
          rotateY: 22,
          rotate: -4,
          borderRadius: 16,
          shadow: "0 25px 50px -12px rgba(0, 0, 0, 0.65)",
        },
        isVisible: true,
        isLocked: false,
      },
      {
        id: "triptych_right",
        type: "image",
        name: "Right Card",
        src: "",
        isPlaceholder: true,
        placeholderLabel: "Right Card",
        width: 260,
        height: 380,
        position: { x: 600, y: 75 },
        style: {
          ...DEFAULT_IMAGE_STYLE,
          rotateX: 6,
          rotateY: -22,
          rotate: 4,
          borderRadius: 16,
          shadow: "0 25px 50px -12px rgba(0, 0, 0, 0.65)",
        },
        isVisible: true,
        isLocked: false,
      },
      {
        id: "triptych_center",
        type: "image",
        name: "Center Card",
        src: "",
        isPlaceholder: true,
        placeholderLabel: "Center Card",
        width: 260,
        height: 395,
        position: { x: 350, y: 65 },
        style: {
          ...DEFAULT_IMAGE_STYLE,
          rotateX: 4,
          rotateY: 0,
          rotate: 0,
          borderRadius: 16,
          shadow: "0 35px 60px -15px rgba(0, 0, 0, 0.75)",
        },
        isVisible: true,
        isLocked: false,
      },
    ],
  },
  {
    id: "isometric-trio",
    title: "Angled Trio",
    description: "Three overlapping fanned cards with natural angles and elevation depth.",
    category: "cards",
    layoutType: "isometric-trio",
    aspectRatio: ASPECT_RATIOS.find((r) => r.name === "16:9") || ASPECT_RATIOS[0],
    elements: [
      {
        id: "iso_1",
        type: "image",
        name: "Card 1",
        src: "",
        isPlaceholder: true,
        placeholderLabel: "Card 1",
        width: 270,
        height: 380,
        position: { x: 140, y: 85 },
        style: {
          ...DEFAULT_IMAGE_STYLE,
          rotateX: 10,
          rotateY: 15,
          rotate: -10,
          borderRadius: 16,
          shadow: "0 25px 50px -12px rgba(0, 0, 0, 0.6)",
        },
        isVisible: true,
        isLocked: false,
      },
      {
        id: "iso_2",
        type: "image",
        name: "Card 2",
        src: "",
        isPlaceholder: true,
        placeholderLabel: "Card 2",
        width: 270,
        height: 390,
        position: { x: 345, y: 70 },
        style: {
          ...DEFAULT_IMAGE_STYLE,
          rotateX: 8,
          rotateY: 0,
          rotate: 0,
          borderRadius: 16,
          shadow: "0 30px 60px -15px rgba(0, 0, 0, 0.65)",
        },
        isVisible: true,
        isLocked: false,
      },
      {
        id: "iso_3",
        type: "image",
        name: "Card 3",
        src: "",
        isPlaceholder: true,
        placeholderLabel: "Card 3",
        width: 270,
        height: 380,
        position: { x: 550, y: 85 },
        style: {
          ...DEFAULT_IMAGE_STYLE,
          rotateX: 10,
          rotateY: -15,
          rotate: 10,
          borderRadius: 16,
          shadow: "0 35px 70px -15px rgba(0, 0, 0, 0.7)",
        },
        isVisible: true,
        isLocked: false,
      },
    ],
  },
  {
    id: "mobile-showcase",
    title: "Mobile Brand Showcase",
    description: "Three mobile device displays with rounded corners for app and UI presentations.",
    category: "mobile",
    layoutType: "mobile-showcase",
    aspectRatio: ASPECT_RATIOS.find((r) => r.name === "16:9") || ASPECT_RATIOS[0],
    elements: [
      {
        id: "phone_left",
        type: "image",
        name: "Left Phone",
        src: "",
        isPlaceholder: true,
        placeholderLabel: "Left Screen",
        width: 200,
        height: 390,
        position: { x: 145, y: 75 },
        style: {
          ...DEFAULT_IMAGE_STYLE,
          rotateX: 6,
          rotateY: 20,
          rotate: -3,
          borderRadius: 24,
          shadow: "0 25px 50px -12px rgba(0, 0, 0, 0.65)",
        },
        isVisible: true,
        isLocked: false,
      },
      {
        id: "phone_center",
        type: "image",
        name: "Center Phone",
        src: "",
        isPlaceholder: true,
        placeholderLabel: "Main Screen",
        width: 200,
        height: 400,
        position: { x: 385, y: 65 },
        style: {
          ...DEFAULT_IMAGE_STYLE,
          rotateX: 4,
          rotateY: 0,
          rotate: 0,
          borderRadius: 24,
          shadow: "0 35px 60px -15px rgba(0, 0, 0, 0.75)",
        },
        isVisible: true,
        isLocked: false,
      },
      {
        id: "phone_right",
        type: "image",
        name: "Right Phone",
        src: "",
        isPlaceholder: true,
        placeholderLabel: "Right Screen",
        width: 200,
        height: 390,
        position: { x: 625, y: 75 },
        style: {
          ...DEFAULT_IMAGE_STYLE,
          rotateX: 6,
          rotateY: -20,
          rotate: 3,
          borderRadius: 24,
          shadow: "0 25px 50px -12px rgba(0, 0, 0, 0.65)",
        },
        isVisible: true,
        isLocked: false,
      },
    ],
  },
  {
    id: "staggered-cascade",
    title: "Staggered Cascade",
    description: "Three descending cards showcasing product flow or multi-step screens.",
    category: "presentation",
    layoutType: "stagger-cascade",
    aspectRatio: ASPECT_RATIOS.find((r) => r.name === "16:9") || ASPECT_RATIOS[0],
    elements: [
      {
        id: "cascade_1",
        type: "image",
        name: "Step 1",
        src: "",
        isPlaceholder: true,
        placeholderLabel: "Step 1",
        width: 340,
        height: 220,
        position: { x: 100, y: 60 },
        style: {
          ...DEFAULT_IMAGE_STYLE,
          rotateX: 6,
          rotateY: -10,
          rotate: -4,
          borderRadius: 16,
          shadow: "0 20px 40px -10px rgba(0, 0, 0, 0.55)",
        },
        isVisible: true,
        isLocked: false,
      },
      {
        id: "cascade_2",
        type: "image",
        name: "Step 2",
        src: "",
        isPlaceholder: true,
        placeholderLabel: "Step 2",
        width: 340,
        height: 220,
        position: { x: 310, y: 155 },
        style: {
          ...DEFAULT_IMAGE_STYLE,
          rotateX: 6,
          rotateY: -10,
          rotate: -4,
          borderRadius: 16,
          shadow: "0 25px 50px -12px rgba(0, 0, 0, 0.6)",
        },
        isVisible: true,
        isLocked: false,
      },
      {
        id: "cascade_3",
        type: "image",
        name: "Step 3",
        src: "",
        isPlaceholder: true,
        placeholderLabel: "Step 3",
        width: 340,
        height: 220,
        position: { x: 520, y: 250 },
        style: {
          ...DEFAULT_IMAGE_STYLE,
          rotateX: 6,
          rotateY: -10,
          rotate: -4,
          borderRadius: 16,
          shadow: "0 30px 60px -15px rgba(0, 0, 0, 0.65)",
        },
        isVisible: true,
        isLocked: false,
      },
    ],
  },
  {
    id: "dual-perspective",
    title: "Dual Perspective Split",
    description: "Two large inward-facing cards for side-by-side product or design comparisons.",
    category: "presentation",
    layoutType: "dual-perspective",
    aspectRatio: ASPECT_RATIOS.find((r) => r.name === "16:9") || ASPECT_RATIOS[0],
    elements: [
      {
        id: "dual_left",
        type: "image",
        name: "Card Left",
        src: "",
        isPlaceholder: true,
        placeholderLabel: "Side A",
        width: 330,
        height: 400,
        position: { x: 130, y: 70 },
        style: {
          ...DEFAULT_IMAGE_STYLE,
          rotateX: 4,
          rotateY: 20,
          rotate: -2,
          borderRadius: 16,
          shadow: "0 30px 60px -15px rgba(0, 0, 0, 0.65)",
        },
        isVisible: true,
        isLocked: false,
      },
      {
        id: "dual_right",
        type: "image",
        name: "Card Right",
        src: "",
        isPlaceholder: true,
        placeholderLabel: "Side B",
        width: 330,
        height: 400,
        position: { x: 500, y: 70 },
        style: {
          ...DEFAULT_IMAGE_STYLE,
          rotateX: 4,
          rotateY: -20,
          rotate: 2,
          borderRadius: 16,
          shadow: "0 30px 60px -15px rgba(0, 0, 0, 0.65)",
        },
        isVisible: true,
        isLocked: false,
      },
    ],
  },
  {
    id: "floating-stack",
    title: "Floating Layered Stack",
    description: "Three vertically stacked cards with depth, elevation, and focused center.",
    category: "cards",
    layoutType: "floating-stack",
    aspectRatio: ASPECT_RATIOS.find((r) => r.name === "16:9") || ASPECT_RATIOS[0],
    elements: [
      {
        id: "stack_back",
        type: "image",
        name: "Back Layer",
        src: "",
        isPlaceholder: true,
        placeholderLabel: "Back Layer",
        width: 400,
        height: 260,
        position: { x: 280, y: 60 },
        style: {
          ...DEFAULT_IMAGE_STYLE,
          scale: 90,
          opacity: 75,
          borderRadius: 16,
          shadow: "0 15px 30px -10px rgba(0, 0, 0, 0.5)",
        },
        isVisible: true,
        isLocked: false,
      },
      {
        id: "stack_mid",
        type: "image",
        name: "Middle Layer",
        src: "",
        isPlaceholder: true,
        placeholderLabel: "Middle Layer",
        width: 400,
        height: 260,
        position: { x: 280, y: 140 },
        style: {
          ...DEFAULT_IMAGE_STYLE,
          scale: 95,
          opacity: 90,
          borderRadius: 16,
          shadow: "0 25px 45px -12px rgba(0, 0, 0, 0.6)",
        },
        isVisible: true,
        isLocked: false,
      },
      {
        id: "stack_front",
        type: "image",
        name: "Front Layer",
        src: "",
        isPlaceholder: true,
        placeholderLabel: "Main Layer",
        width: 400,
        height: 260,
        position: { x: 280, y: 220 },
        style: {
          ...DEFAULT_IMAGE_STYLE,
          scale: 100,
          opacity: 100,
          borderRadius: 16,
          shadow: "0 35px 60px -15px rgba(0, 0, 0, 0.7)",
        },
        isVisible: true,
        isLocked: false,
      },
    ],
  },
];
